import type { Metadata } from "next";
import { Footer, Header } from "../components";

export const metadata: Metadata = { title: "Install Agent Memory — RecursiveIntell", description: "Six verified paths to install RecursiveIntell agent memory for coding hosts, MCP clients, and Rust applications." };

const recipes = [
  { index: "01 / RECOMMENDED", title: "Claude Code · plugin path", body: "The fastest operator path. The kit installs lifecycle hooks, MCP configuration, setup, ingestion, doctors, and evidence workflows.", code: "/plugin marketplace add RecursiveIntell/agent-memory-kits\n/plugin install semantic-memory@semantic-memory-kit\n/memory-setup", steps: ["Restart Claude Code once so the new hooks load.", "Run /memory-ingest . inside a repository you actually use.", "Run the doctor, then ask about the ingested codebase."], note: "A new store returning no recall is expected; recall fails open until there are facts worth retrieving.", href: "https://github.com/RecursiveIntell/agent-memory-kits/tree/main/claude" },
  { index: "02 / HOOK TIER", title: "Codex CLI · plugin path", body: "A hook-capable Codex integration with MCP configuration, Python lifecycle hooks, prompts, skills, doctors, ingestion, and audit helpers.", code: "git clone https://github.com/RecursiveIntell/agent-memory-kits\ncd agent-memory-kits\ncodex plugin marketplace add ./codex\ncodex plugin add semantic-memory@semantic-memory-codex-kit", steps: ["Choose one canonical memory directory for every project.", "Use one owner for any warm HTTP port.", "Run the Codex doctor, ingest a real repository, then test recall."], note: "Day 1 starts empty. Test recall after ingesting or deliberately capturing facts.", href: "https://github.com/RecursiveIntell/agent-memory-kits/tree/main/codex" },
  { index: "03 / PLUGIN + MCP", title: "Hermes Agent", body: "Copy and enable the Hermes plugin, register semantic-memory as an MCP server, and test the connection Hermes will actually use.", code: "git clone https://github.com/RecursiveIntell/agent-memory-kits\ncd agent-memory-kits\ncp -R hermes \"$HOME/.hermes/plugins/semantic-memory-mcp\"\nhermes plugins enable semantic-memory-mcp\nhermes mcp add semantic_memory --command semantic-memory-mcp \\\n  --args --memory-dir \"$HOME/.local/share/semantic-memory\" --tool-profile agent\nhermes mcp configure semantic_memory\nhermes mcp list\nhermes mcp test semantic_memory", steps: ["Keep --args last; it consumes all remaining arguments.", "Restart Hermes after installing or changing plugin code.", "Confirm mcp list and mcp test, then ingest real work."], note: "Use the plugin and MCP commands instead of hand-editing legacy configuration as the primary path.", href: "https://github.com/RecursiveIntell/agent-memory-kits/tree/main/hermes" },
  { index: "04 / SIX HOSTS", title: "MCP + rules tier", body: "For Cursor, Cline, Roo Code, Windsurf, Continue, and OpenCode: MCP tools plus explicit host-native rule and context files.", code: "git clone https://github.com/RecursiveIntell/agent-memory-kits\ncd agent-memory-kits\ncursor/scripts/setup.sh --write-project /path/to/project\nshared/scripts/doctor-all.py --deep", steps: ["Replace cursor with the directory for your supported host.", "Let setup write project or user MCP and rule files.", "Run the deep shared doctor and inspect what your host loads."], note: "This tier does not claim hidden prompt, session, or compaction hooks. The host or agent must invoke MCP workflows.", href: "https://github.com/RecursiveIntell/agent-memory-kits#per-host-docs" },
  { index: "05 / PROTOCOL", title: "Direct Semantic Memory MCP", body: "Install the published Rust binary, point it at one canonical local memory directory, and start with the bounded agent profile.", code: "cargo install semantic-memory-mcp --locked --version '=0.5.4'\nsemantic-memory-mcp \\\n  --memory-dir \"$HOME/.local/share/semantic-memory\" \\\n  --tool-profile agent", steps: ["Install the exact repository-matched 0.5.4 server version.", "Use tools/list as runtime truth for the active binary and profile.", "Run a witnessed search and inspect the returned receipt."], note: "Source, published package, live artifact, and receipt evidence remain distinct scopes.", href: "https://github.com/RecursiveIntell/semantic-memory-mcp" },
  { index: "06 / RUST API", title: "Semantic Memory library", body: "Embed the SQLite-authoritative retrieval core directly. Begin with a deterministic embedder before choosing a production model boundary.", code: "cargo add semantic-memory@0.5.11\n# Start with the deterministic MockEmbedder quick start\n# before selecting a production embedder.", steps: ["Use MockEmbedder to verify storage and retrieval deterministically.", "Choose a production embedder and make its network/model boundary explicit.", "Evaluate on your corpus before enabling optional research modules."], note: "SQLite is authoritative. Indexes and vector artifacts accelerate retrieval and must remain rebuildable.", href: "https://github.com/RecursiveIntell/semantic-memory" },
] as const;

export default function InstallPage() {
  return <><Header current="install" /><main id="main"><section className="route-hero"><div className="grid-bg" aria-hidden="true" /><div className="wrap route-hero-grid"><div><span className="eyebrow">Installation field guide · six supported paths</span><h1>Install memory. <em>Then prove it works.</em></h1><p className="lede">Every path ends the same way: install, restart, ingest, doctor, recall. Start with the host you already use.</p></div><aside className="route-card"><small>BEFORE YOU PASTE</small><strong>Git · Python 3 · Rust + cargo</strong><p>Install your coding host first. Put semantic-memory-mcp on PATH for direct integrations. The first local embedding run may download a model.</p></aside></div></section>
    <section className="section paper"><div className="wrap"><div className="section-head"><div><span className="kicker">01 · THE LOOP</span><h2>Five steps from install to useful recall.</h2></div><p>Do not judge a clean store before ingesting real work. Each recipe makes the verification boundary explicit.</p></div><div className="install-intro">{[["01","Install","Use one canonical path."],["02","Restart","Reload hook-capable hosts."],["03","Ingest","Index a real repository."],["04","Doctor","Check binaries, profiles, storage."],["05","Recall","Ask about the work you ingested."]].map(([n,t,b]) => <div key={n}><small>{n}</small><b>{t}</b><p>{b}</p></div>)}</div></div></section>
    <section className="section"><div className="wrap"><div className="section-head"><div><span className="kicker">02 · CHOOSE A PATH</span><h2>Use the narrowest integration that fits.</h2></div><p>Hook-capable hosts can recall automatically. Rules-tier hosts expose MCP tools and explicit guidance without pretending a rules file is a lifecycle hook.</p></div>{recipes.map((recipe) => <article className="recipe" key={recipe.index}><div className="recipe-index">{recipe.index}</div><div><h2>{recipe.title}</h2><p>{recipe.body}</p><pre><code>{recipe.code}</code></pre><ol>{recipe.steps.map((step) => <li key={step}>{step}</li>)}</ol><p><strong>Boundary:</strong> {recipe.note}</p><a href={recipe.href} target="_blank" rel="noreferrer">Open canonical integration docs ↗</a></div></article>)}</div></section>
    <section className="section paper"><div className="wrap method-grid"><div><span className="kicker">03 · DAY-ONE VERIFICATION</span><h2>A green install is not useful memory yet.</h2><p>Verify the actual runtime surface, ingest something you understand, and ask a question whose answer you can check.</p></div><ol><li>Confirm the binary or plugin is discoverable.</li><li>Inspect the active MCP profile with <code>tools/list</code>.</li><li>Ingest a repository and check that facts were written.</li><li>Run the host-specific doctor and retain its output.</li><li>Ask one answerable codebase question and inspect its receipt.</li><li>Test the empty/degraded path: missing memory must not block your prompt.</li></ol></div></section>
  </main><Footer /></>;
}
