import type { Metadata } from "next";
import Link from "next/link";
import { Footer, Header } from "../components";

export const metadata: Metadata = { title: "How the System Thinks — RecursiveIntell", description: "The RecursiveIntell field manual for memory, time, receipts, typed boundaries, replay, and measured compression." };

const chapters = [
  { id: "memory", number: "01 / MEMORY", title: "Memory is not authority.", definition: "Memory preserves searchable state. Authority decides whether a claim may be trusted or an action may be taken. Combining those jobs turns retrieved text into accidental policy.", contrasts: ["Remembered ≠ verified", "Relevant ≠ authorized", "Local ≠ encrypted"], example: "semantic-memory + claim-ledger", proof: "SQLite owns durable searchable facts. A separately verified ledger can enrich trust without becoming a shadow memory database.", failure: "Ledger verification failure disables enrichment and writes; ordinary memory retrieval continues without promotion." },
  { id: "time", number: "02 / TIME", title: "Truth has a valid time and a recorded time.", definition: "A system can know when a statement became true in the world and when it learned that statement. Bitemporal state keeps corrections, supersession, and historical queries honest.", contrasts: ["Valid time", "Transaction time", "Current / historical / as-of"], example: "bitemporal-runtime + living-memory", proof: "Current, historical, and as-of views remain explicit instead of collapsing every update into the latest prose.", failure: "Ranking must not answer with a superseded decision while hiding its state." },
  { id: "receipts", number: "03 / RECEIPTS", title: "Receipts are evidence, not correctness.", definition: "A receipt records an execution path, selected backend, state view, degradations, retained inputs, and outcome. It makes an operation inspectable; it does not make the result true.", contrasts: ["Source scope", "Package scope", "Live scope", "Execution scope"], example: "claim-ledger + receipt-bench", proof: "Observed evidence stays bound to the command, artifact, backend, and inputs that actually produced it.", failure: "A receipt cannot prove factual truth, total correctness, security, or action permission." },
  { id: "boundaries", number: "04 / BOUNDARIES", title: "Typed failure is part of the product.", definition: "A bounded system distinguishes completion, interruption, rejection, degradation, and failure. Converting an error into a successful-looking state is false success.", contrasts: ["Typed context", "Admission", "Effect", "Witness", "Settlement"], example: "llm-tool-runtime + verification-policy", proof: "Tool results and policy decisions retain structured failure and reason codes across execution boundaries.", failure: "Ordinary execution error must never become Complete; missing governance must never become Allow." },
  { id: "acceleration", number: "05 / ACCELERATION", title: "Indexes accelerate truth. They do not own it.", definition: "FTS tables, vector indexes, quantized candidates, caches, and graph projections may improve retrieval. Each remains derived, reconcilable, and rebuildable from a canonical owner.", contrasts: ["SQLite · canonical", "Indexes · derived", "Receipts · observed"], example: "semantic-memory", proof: "SQLite owns facts, state, raw embeddings, and receipts. Search artifacts can be rebuilt or exactly bypassed where configured.", failure: "Strict search stops on corrupt state; opt-in degradation names exact omissions." },
  { id: "compression", number: "06 / COMPRESSION", title: "Compression is measured, governed, and reversible.", definition: "A codec has a wire format, profile digest, quality budget, resource limit, score semantics, and unsupported paths. It is not a marketing adjective.", contrasts: ["turbo-quant · hot", "fib-quant · cold", "poly-kv · pool policy"], example: "quant-codec-core + quant-governor", proof: "Quality and latency claims remain bound to dataset, hardware, commit, codec, and exact fallback behavior.", failure: "Compressed bytes cannot pose as original vectors; unavailable decode paths return typed errors." },
  { id: "replay", number: "07 / REPLAY", title: "Replay depends on what was deliberately retained.", definition: "A receipt can identify a past execution without containing enough material to reproduce it. Complete replay is opt-in because prompts, context, and retrieved content carry privacy and storage costs.", contrasts: ["Replayable · retained", "No replay · receipt only", "Degraded · material unavailable"], example: "semantic-memory-mcp + context governor", proof: "Contradiction, supersession, and selective forgetting remain explicit lifecycle operations with inspectable outcomes.", failure: "Deletion from an index is not proof of deletion from every canonical or fallback store." },
] as const;

export default function ConceptsPage() {
  return <><Header current="concepts" /><main id="main"><section className="route-hero"><div className="grid-bg" aria-hidden="true" /><div className="wrap route-hero-grid"><div><span className="eyebrow">RecursiveIntell field manual</span><h1>How the system <em>thinks.</em></h1><p className="lede">Eight ideas explain the architecture: memory is not authority, time has more than one axis, receipts are evidence rather than correctness, and acceleration must remain recoverable.</p></div><aside className="route-card"><small>MANUAL / 01</small><strong>Trust is a composition.</strong><p>No database, model, receipt, policy, or benchmark carries the whole claim. The boundaries between them are the design.</p><a href="#memory">Begin with memory →</a></aside></div></section>
    <nav className="chapter-nav" aria-label="Field manual chapters"><div className="wrap">{[...chapters.map((chapter) => [chapter.id,chapter.id]),["ownership","ownership"]].map(([href,label]) => <a key={href} href={`#${href}`}>{label}</a>)}</div></nav>
    {chapters.map((chapter) => <section className="chapter" id={chapter.id} key={chapter.id}><div className="wrap chapter-grid"><div className="chapter-number">{chapter.number}</div><div className="chapter-copy"><h2>{chapter.title}</h2><p>{chapter.definition}</p><div className="contrast">{chapter.contrasts.map((value) => <span key={value}>{value}</span>)}</div></div><aside className="chapter-proof"><small>LIBRARY EXAMPLE</small><strong>{chapter.example}</strong><p>{chapter.proof}</p><em>{chapter.failure}</em></aside></div></section>)}
    <section className="chapter" id="ownership"><div className="wrap"><div className="chapter-number">08 / OWNERSHIP</div><div className="section-head"><div><h2>Every artifact needs one canonical owner.</h2></div><p>Recovery and trust become tractable when durable state, derived acceleration, execution evidence, context fallback, and claim authority do not compete.</p></div><div className="ownership-wrap" tabIndex={0}><table className="ownership-table"><thead><tr><th>Artifact</th><th>Canonical owner</th><th>Recoverability</th><th>Claim boundary</th></tr></thead><tbody><tr><td>Searchable memory</td><td>SQLite memory.db</td><td>WAL, integrity, FTS/vector reconciliation</td><td>Local store ≠ encrypted store</td></tr><tr><td>Vector acceleration</td><td>Derived index or candidate artifact</td><td>Rebuild or exact f32 fallback</td><td>Index ≠ source of truth</td></tr><tr><td>Search execution</td><td>Durable retrieval receipt</td><td>Replay only with retained inputs</td><td>Receipt ≠ factual truth</td></tr><tr><td>Compacted context</td><td>Context Governor receipt store</td><td>Exact expansion of fallback records</td><td>Recoverability ≠ task success</td></tr><tr><td>Claim trust</td><td>Verified claim-ledger history</td><td>Hash chain, snapshot, retained-tail verification</td><td>Trust ≠ action authority</td></tr></tbody></table></div></div></section>
    <section className="section"><div className="wrap"><div className="section-head"><div><span className="kicker">CONTINUE THE INSPECTION</span><h2>Move from language to artifacts.</h2></div><p>The Atlas maps these concepts to concrete packages. Activity shows what changed. Install turns one product path into a working local system.</p></div><div className="route-grid three"><Link href="/libraries"><small>01</small><h3>Library Atlas</h3><p>Every audited package.</p><b>Open the atlas →</b></Link><Link href="/activity"><small>02</small><h3>Activity</h3><p>Public engineering signal.</p><b>See what moved →</b></Link><Link href="/install"><small>03</small><h3>Install</h3><p>Six verified paths.</p><b>Get started →</b></Link></div></div></section>
  </main><Footer /></>;
}
